import { Type } from "typebox";
import { createKickoff, postComment, readRoster, resolveRecipient, signedBody, writeRoster } from "./comm.mjs";
const result=value=>({content:[{type:"text",text:JSON.stringify(value)}],details:value});
const path=(cwd,runId)=>`${cwd}/.pi/fabric/crew-launch/${runId}-roster.json`;
const sender={from:Type.String(),signature:Type.String({description:"Completed funny signature from your persona"})};
export function registerCommunicationTools(pi) {
  pi.registerTool({name:"crew_kickoff",label:"Crew: create kickoff",description:"Create the canonical signed Discussion.",parameters:Type.Object({runId:Type.String(),title:Type.String(),body:Type.String(),category:Type.Optional(Type.String()),...sender}),async execute(_id,input,_s,_u,ctx){const p=path(ctx.cwd,input.runId),r=readRoster(p);if(r.discussionNumber)throw new Error(`Crew ${input.runId} already has a Discussion`);const d=createKickoff(r,input.title,signedBody(r,input.from,input.body,input.signature),input.category);writeRoster(p,{...r,discussionNumber:d.number,discussionUrl:d.url});return result({discussionNumber:d.number,discussionUrl:d.url});}});
  pi.registerTool({name:"crew_post",label:"Crew: post finding",description:"Post a signed substantive finding or review.",parameters:Type.Object({runId:Type.String(),message:Type.String(),...sender}),async execute(_id,input,_s,_u,ctx){const r=readRoster(path(ctx.cwd,input.runId));return result({commentUrl:postComment(r,signedBody(r,input.from,input.message,input.signature)).url});}});
  for(const [name,field,prefix] of [["crew_tell","message",""],["crew_ask","question","[QUESTION]\\n\\n"]])pi.registerTool({name,label:`Crew: ${name==="crew_tell"?"tell member":"ask member"}`,description:"Post a signed substantive directed message.",parameters:Type.Object({runId:Type.String(),to:Type.String(),[field]:Type.String(),...sender}),async execute(_id,input,_s,_u,ctx){const r=readRoster(path(ctx.cwd,input.runId)),to=resolveRecipient(r,input.to);const body=`@${to.name}\\n\\n${prefix}${input[field]}`;return result({actorId:to.actorId,commentUrl:postComment(r,signedBody(r,input.from,body,input.signature)).url});}});
  pi.registerTool({name:"crew_broadcast",label:"Crew: broadcast",description:"Post a signed shared decision.",parameters:Type.Object({runId:Type.String(),message:Type.String(),...sender}),async execute(_id,input,_s,_u,ctx){const r=readRoster(path(ctx.cwd,input.runId));return result({commentUrl:postComment(r,signedBody(r,input.from,`[BROADCAST]\\n\\n${input.message}`,input.signature)).url,topic:r.topic});}});
}
